#!/usr/bin/env bash

SYMBOLS_TO_MANGLE=(
    "CBOR"
    "CBORRepresentable"
    "ObjCCBORDecodingErrorDomain"
    "ObjCCBOREncodingErrorDomain"
    "DSCborBase64DataMarker"
)

cat > "$OBJC_CBOR_MANGLING_HEADER" << EOF

// --------------------------------------------------------------------------------
// WARNING: This header is generated by Scripts/ObjCCBORGenerateManglingHeader.sh.
// Pleaes DO NOT modify its contents manually. Update the script if needed instead.
// --------------------------------------------------------------------------------

#ifndef OBJC_CBOR_MANGLING_H
#define OBJC_CBOR_MANGLING_H

EOF

for symbol in "${SYMBOLS_TO_MANGLE[@]}"
do
  echo "#define $symbol $OBJC_CBOR_MANGLING_PREFIX$symbol" >> "$OBJC_CBOR_MANGLING_HEADER"
done

cat >> "$OBJC_CBOR_MANGLING_HEADER" << EOF

#endif /* OBJC_CBOR_MANGLING_H */
EOF
