name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        recursive: true

    - name: Test
      run: set -o pipefail &&
           xcodebuild test 
           -enableCodeCoverage YES 
           -project TinyCborObjc.xcodeproj 
           -scheme TinyCborObjc 
           -destination 'platform=iOS Simulator,name=iPhone 11' 
           ONLY_ACTIVE_ARCH=NO 
           | xcpretty
           
    - name: PodLint
      run: pod lib lint
